### ISSUE TITLE
Cannot minimise window.

### ISSUE THREAD

**Issue by Gh0stBlade** [thedmd/imgui-node-editor#82]
If the Editor is inside a window or child window it cannot be minimised it simply messes up the entire rendering of ImGui. It looks to be framebuffer related.

Examples:

1. Before minimise.
![image](https://user-images.githubusercontent.com/6951235/93714488-e375d480-fb5a-11ea-9dd9-8f12c2f4693f.png)

2. After minimise.
![image](https://user-images.githubusercontent.com/6951235/93714496-fb4d5880-fb5a-11ea-9ec1-e517165b60d1.png)

You should notice that in the above image the main ui render target is off centered and not properly rendered. In some cases it looks way worse than this.

3. After relaunching the application and launching the Editor. It simply renders nothing.
![image](https://user-images.githubusercontent.com/6951235/93714529-2d5eba80-fb5b-11ea-90c2-5a5f6471e84b.png)

**Comment by thedmd** [comment]
Can you tell if editor is updated when it's window is minimized?

**Comment by Gh0stBlade** [comment]
Looks like all the code is executed when the window is minimised.

**Comment by thedmd** [comment]
Does it help if you skip calling the editor when window is minimized?

**Comment by Gh0stBlade** [comment]
If i skip everything between ed::begin and ed::end there are no issues.

**Comment by thedmd** [comment]
I will guard the code for that case.

**Comment by thedmd** [comment]
@Gh0stBlade Issue is fixed on develop branch. I'm punching out there fixes for other issues before making a release. So it is as stable as it can get.

**Comment by Gh0stBlade** [comment]
Not fixed at all in develop, I have exactly the same issues but worse.

**Comment by thedmd** [comment]
Thanks for an update. I suspect this may be related to mouse being moved to (-1, -1) when focus is lost.
Can you confirm this?

**Comment by thedmd** [comment]
There was a fix for dragging shooting to infinity when window loose focus. Can you it? It is on develop.

Can you tell me what size is sent to ed::Begin() when window is minimized?

Can you reproduce this bug with on of the examples?

**Comment by Gh0stBlade** [comment]
I can confirm this is still not fixed, will investigate further. It might be a rendertarget issue.

**Comment by thedmd** [comment]
@Gh0stBlade Hello, did you found a bug maybe?

**Comment by Gh0stBlade** [comment]
It seems like it's writing to an invalid rendertarget when I do the bug steps to reproduce this. I checked this in renderdoc. My editor is using deferred rendering, no idea why this is happening.

**Comment by thedmd** [comment]
Editor does not have control over that. Always use current ImGui context and current window. Is this by chance an issue of not setting correct context (editors orx imgui)?
